// <auto-generated />
namespace DigiTools.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class campos_usuarios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(campos_usuarios));
        
        string IMigrationMetadata.Id
        {
            get { return "201810091613594_campos_usuarios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
